spring.profiles.active: local

spring:
  config:
    import:
      - application-db.yml
  web:
    resources:
      add-mappings: false

logging:
  level:
    com.kookmin.api: DEBUG
    org.springframework.security: DEBUG
